name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Change this to your main branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14 # Change this to your Node.js version

      - name: Install dependencies
        run: npm install # or yarn install if you use Yarn

      - name: Build
        run: npm run build # Replace with your build command

      - name: Deploy to GitHub Pages
        run: |
          if [ -z "$GITHUB_TOKEN" ]; then
            echo "Set the GITHUB_TOKEN secret in your repository settings."
            exit 1
          fi
          echo "Publishing to GitHub Pages..."
          npx gh-pages -d out # Change 'out' to your build output directory
